apiVersion: skaffold/v2beta10
kind: Config
metadata:
  name: skaffold-create-react-app
build:
  artifacts:
  - image: skaffold-create-react-app
    sync:
      infer:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.css'
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - k8s/deployment.yaml
portForward:
- resourceType: deployment
  resourceName: create-react-app
  port: 3000
