apiVersion: apps/v1
kind: Deployment
metadata:
  name: create-react-app
spec:
  selector:
    matchLabels:
      app: create-react-app
  template:
    metadata:
      labels:
        app: create-react-app
    spec:
      containers:
      - name: create-react-app
        image: skaffold-create-react-app
        ports:
        - containerPort: 3000
